# NUMPY

In [2]:
import numpy as np

In [4]:
cvalues=[25,56,34.5,24.3,14.5]
print(type(cvalues))
print(cvalues)

<class 'list'>
[25, 56, 34.5, 24.3, 14.5]


In [8]:
C=np.array(cvalues)
print(C)
print(type(C))

[25.  56.  34.5 24.3 14.5]
<class 'numpy.ndarray'>


In [10]:
fvalues=[]
print("Using normal method:")
for x in cvalues:
    fvalues.append(x*9/5+32)
print(fvalues,'\n')

Using normal method:
[77.0, 132.8, 94.1, 75.74000000000001, 58.1] 



In [17]:
# 1-D array
a=np.array([1,2,3])
print(a)
print()

#2-D array
b=np.array([[1,2],[2,3]])
print(b)
print()

#minimum dimmenssion
c=np.array([1,2,3,4,5,6,],ndmin=3)
#here the min dimenssion is 2,
print(c)

[1 2 3]

[[1 2]
 [2 3]]

[[[1 2 3 4 5 6]]]


# DDD

In [20]:
dt=np.dtype(np.int32) # 32 bits=4bytes
print(dt)

dt=np.dtype('i4') # 32 bits=4bytes
print(dt)

int32
int32


# Attributes

In [21]:
b=np.array([[1,2,3],[2,3,4]])
print(b.shape) #.shape shws the shape of the array(means gave the number of rows and columns)
print(b) #print the array

(2, 3)
[[1 2 3]
 [2 3 4]]


In [25]:
b.shape=(3,2) #change the dimenssion of the array 
print(b)

[[1 2]
 [3 2]
 [3 4]]


In [27]:
b=np.array([[1,2,3],[2,3,4]])
c=b.reshape(3,2) # reshape the dimenssions
print(c)

[[1 2]
 [3 2]
 [3 4]]


In [32]:
a=np.arange(24) #arrange the value upto value in the ()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [33]:
#above id 1-D array
print(a.ndim)

1


In [35]:
b=a.reshape(2,4,3)  #2.3.4.=24
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [36]:
# dtpye of array is float32 (4byte)
x=np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

4


In [54]:
# first creat the structure data type
dt=np.dtype([('age', np.int8),('weight',np.int32)])  #int8=1byte
print(dt)

[('age', 'i1'), ('weight', '<i4')]


In [44]:
#now apply it to ndarray object
a=np.array([(10,35),(25,50),(65,90)],dt)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[(10, 35) (25, 50) (65, 90)]


In [45]:
print(a['age'])

[10 25 65]


# Flags 

In [5]:
x=np.array([1,2,3,4,5,])
print(x.flags)

NameError: name 'np' is not defined

In [6]:
print(x.flags['WRITEABLE'])

NameError: name 'x' is not defined

In [7]:
x[3]=21
print(x)

NameError: name 'x' is not defined

In [4]:
x.flags['WRITEABLE']=False # here writeable condition is false so we can't write or change the array
x[3]=54
print(x)

NameError: name 'x' is not defined